### ISSUE TITLE
Host Leaves Game -- crash (Kama Simon)

### ISSUE THREAD

**Issue by gerylkvinoya** [torkelso19/Labyrinth#3]
Step to Recreate:
1. run the game (network)
2.host leaves game
3.game crashes/unable to continue play
--------------------------
On Phillips tablet it just crashed (don't know why) but he ended up leaving the game and the rest of us were unable to play the game.

**Comment by torkelso19** [comment]
Yes that is expected behavior. You cannot quit the game

**Comment by gerylkvinoya** [comment]
Ok.
