### ISSUE TITLE
Rules/Help button

### ISSUE THREAD

**Issue by gerylkvinoya** [torkelso19/Labyrinth#5]
Steps to recreate:
1. run the game
2. play remote or local game
3. click on the rules/help button

Just a problem with exiting the help menu. A user could go through all of the rules/help but would have to go all the way back to the beginning to exit the menu. Not necessarily bad but an inconvenience

**Comment by torkelso19** [comment]
Yes we were planning on adding a button to escape the rules menu besides scrolling all the way back

**Comment by gerylkvinoya** [comment]
Tested it and escaping the rules menu works.
