### ISSUE TITLE
hard crash

### ISSUE THREAD

**Issue by mooreka21** [torkelso19/Labyrinth#9]
1. start new local game with all smart ai's
2. don't touch anything during your turn
3. screen goes grey
4. eventually game came back up after a while

I have no idea how this happened and I wasn't able to recreate it.

**Comment by torkelso19** [comment]
We have never been able to recreate this. We think it was something going on with the tablet as the game started.

**Comment by mooreka21** [comment]
That makes sense, everything worked perfectly when I tried to recreate this. Great job!!
